apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocketchatdb-dump
  namespace: rocketchat
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: retain-azurefile
  volumeMode: Filesystem