apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocketchat-data
  namespace: rocketchat
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  storageClassName: retain-azurefile
  volumeMode: Filesystem