apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: rocketchat-hpa
  namespace: rocketchat
spec:
  maxReplicas: 3 # define max replica count
  minReplicas: 2  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rocketchat
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 65