apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: mongodb-dev
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standardlrs
  resources:
    requests:
      storage: 10Gi